framework: jest
postMerge:
  env:
      NODE_ENV: development
      npm_lifecycle_event: test
  pattern:
    - "{packages,scripts}/**/__tests__/*{.js,.coffee,[!d].ts}"
preMerge:
  env:
    NODE_ENV: development
    npm_lifecycle_event: test
  pattern:
    - "{packages,scripts}/**/__tests__/*{.js,.coffee,[!d].ts}"
preRun:
  command:
    - yarn
postRun:
  command:
    - node --version
configFile: scripts/jest/config.source-www.js
nodeVersion: 14.17.6
version: 1.1
