---
framework: jest
licenseTier: xsmall
postMerge:
  pattern:
    - "./packages/dom-event-testing-library/__tests__/index-test.internal.js"
    - "./packages/use-sync-external-store/src/__tests__/*-test.js"
    - "./packages/create-subscription/src/__tests__/createSubscription-test.js"
    - "./packages/react-is/src/__tests__/ReactIs-test.js"
    - "./packages/scheduler/src/__tests__/*-test.js"
    - "./packages/scheduler/src/__tests__/*-test.internal.js"
    - "./packages/**/*/__tests__/*-test.internal.js"
    - "./packages/react-native-renderer/src/__tests__/*-test.internal.js"
  strategy:
    threshold: <5|100s|30m|6h>
    type: <commit|time>
preMerge:
  pattern:
    - "./packages/dom-event-testing-library/__tests__/index-test.internal.js"
    - "./packages/use-sync-external-store/src/__tests__/*-test.js"
    - "./packages/create-subscription/src/__tests__/createSubscription-test.js"
    - "./packages/react-is/src/__tests__/ReactIs-test.js"
    - "./packages/scheduler/src/__tests__/*-test.js"
    - "./packages/scheduler/src/__tests__/*-test.internal.js"
    - "./packages/**/*/__tests__/*-test.internal.js"
    - "./packages/react-native-renderer/src/__tests__/*-test.internal.js"
preRun:
     command:
        - yarn install
        - yarn run build
postRun:
     command:
        - yarn --version
version: 2.0
