---
framework: "jest"
postMerge:
  pattern:
    - "./react/src/__tests__/*.js"
preMerge:
  pattern:
    - "./react/src/__tests__/*.js"
preRun:
  - yarn install
postRun:
  - yarn --version
version: 2.0
